server:
  port: 9527

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: parentcloud-zuul-9527  # 默认服务名称的设定

spring:
  application:
    name: parentcloud-zuul


zuul:
  routes:
    mydept:
      path: /ts/**
      serviceId: DEPTCONSUMER-80
  ignored-services: "*"
  prefix: "/api"